### PR TITLE
Update graphql query with item name and sku

### PR DESCRIPTION
**Pull request by Roene-JustBetter**

### CODE REVIEW

**Comment by royduin** [comment]
Maybe extract this part to a partial so everything is using the same? It's also used here: https://github.com/rapidez/account/blob/master/resources/views/account/partials/queries/order.graphql#L44-L49

**Comment by royduin** [comment]
Status?

**Comment by royduin** [comment]
@Roene-JustBetter

**Comment by Roene-JustBetter** [comment]
I don't know why this was needed but I think we don't need it anymore so I will close this Pull Request.

**Pull request closed without merging**
